# https://taskfile.dev
version: '3'

vars:
  BINFILE: httping-go

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  build:
    desc: "Build the binary"
    cmds:
      - go build .

  linter:
    desc: "Run the linter"
    cmds:
      - golangci-lint run

  run:
    desc: "Run the binary"
    cmds:
      - ./{{.BINFILE}} -u https://taskfile.dev

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean
