# https://taskfile.dev
version: '3'

vars:
  BINFILE: httping-go

tasks:
  vulncheck:
    desc: "Scan dependencies for known vulnerabilities"
    cmds:
      - govulncheck ./...

  default:
    desc: "List all tasks"
    cmds:
      - task -a

  build:
    desc: "Build the binary"
    cmds:
      - go build ./cmd/httping-go

  lint:
    desc: "Run the linter"
    cmds:
      - golangci-lint run

  cover:
    desc: "Run tests and report total coverage"
    cmds:
      - go test -coverpkg=./... -coverprofile=profile.cov ./...
      - sed -i '' '/cmd/d' profile.cov
      - go tool cover -func profile.cov | grep '^total:'

  run:
    desc: "Run the binary"
    cmds:
      - ./{{.BINFILE}} -u https://taskfile.dev

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean
