# https://taskfile.dev
version: '3'

vars:
  BINFILE: httping-go

tasks:
  default:
    desc: "Build the binary"
    cmds:
      #- echo "{{.GREETING}}"
      - go build .
      - upx httping-go
    # silent: true
    method: checksum
    generates:
      - "{{.BINFILE}}"

  run:
    desc: "Run the binary"
    deps: 
    - default
    sources:
      - "*.go"
    cmds:
      - ./{{.BINFILE}} -u https://taskfile.dev
