# https://taskfile.dev
version: '3'

vars:
  BINFILE: httping-go

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  build:
    desc: "Build the binary"
    cmds:
      - go build .

  run:
    desc: "Run the binary"
    cmds:
      - ./{{.BINFILE}} -u https://taskfile.dev
